/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every account. */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account. */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one account by ID or unique name. */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /**
         * Archive an account.
         * @description This hides the account from pickers; its history remains. There is no hard delete for an account with any history.
         */
        delete: operations["archiveAccount"];
        options?: never;
        head?: never;
        /**
         * Rename an account, or re-declare its opening balance.
         * @description The request body must set exactly one of "name" or "opening_balance" - these are two separate operations at the application layer, and a request naming both or neither is rejected.
         */
        patch: operations["patchAccount"];
        trace?: never;
    };
    "/api/v1/analytics/average-transaction-size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The mean transaction amount, overall and by top-level category.
         * @description "average" is the mean of each matching posting's absolute amount (a magnitude, not a signed net) - "overall" covers every matching posting; "by_category" breaks that down by top-level category, with an "Uncategorized" row for postings with no category at all. Transfers are excluded by construction.
         */
        get: operations["getAverageTransactionSize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inflow vs. outflow, bucketed by period.
         * @description When the filter sets both "from" and "to", every period in that range is included, even one with no matching postings. "granularity" selects the bucket size - week, month (the default), year, or custom (the whole "from".."to" range as one bucket, which then requires both). Transfers are excluded by construction.
         */
        get: operations["getCashFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/category-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spending and income, by top-level category.
         * @description Every matching posting rolls up into its top-level category (a posting under Groceries or Restaurants both count toward "Food") - an "Uncategorized" row covers postings with no category at all. Transfers are excluded by construction.
         */
        get: operations["getCategoryBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/category-trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Month-over-month (or period-over-period) spending/income change, per category.
         * @description Extends /trends' aggregate-only comparison to one row per top-level category: "granularity" selects the comparison period the same way it does for /trends (week, month - the default, year, or custom). A category present in only one of the two periods still gets a row, zeroed on the side with nothing to report, rather than being omitted. "spending_change_pct"/"income_change_pct" are absent when the previous period's corresponding figure is zero - an undefined ratio, not zero.
         */
        get: operations["getCategoryTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/savings-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Income − outflow) / income, over the filter's date range.
         * @description "rate" is absent when income is zero - an undefined ratio, not zero.
         */
        get: operations["getSavingsRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/top-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The largest transactions in a period, by absolute amount.
         * @description "limit" is the top-N count (defaults to 10, capped at 100) - every matching posting is still fetched and converted first, and only then truncated to the largest "limit" by magnitude. "amount" stays signed (negative for an outflow) even though the sort itself is by magnitude. Transfers are excluded by construction.
         */
        get: operations["getTopTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current period vs. the immediately preceding one.
         * @description "granularity" selects the comparison period - week, month (the default), year, or custom. For week/month/year, "from"/"to" are ignored: this compares the current period against the previous one, in the actor's own timezone. For custom, "from"/"to" (both required) name the current period, compared against the immediately preceding period of the same length. Every other filter dimension still applies to both periods identically.
         */
        get: operations["getTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in and start a session.
         * @description On success, sets an HttpOnly session cookie the browser holds and resends automatically - the response body carries no credential to store.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session.
         * @description Requires a session cookie; a bearer-token request has no session to end - revoke the API token instead.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End every session the acting user has open.
         * @description Revokes every session, including the one that made this request, if any.
         */
        post: operations["logoutAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the acting user's password.
         * @description Revokes every session the acting user has open, including whichever one made this request - it will need to sign in again afterward.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every API token the acting user owns.
         * @description Includes revoked and expired tokens, for history - not only what's currently live.
         */
        get: operations["listAPITokens"];
        put?: never;
        /**
         * Issue a new API token.
         * @description The plaintext token is returned exactly once, in this response - it can't be retrieved again.
         */
        post: operations["createAPIToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API token.
         * @description The token stops authenticating immediately, but remains listed (soft revocation).
         */
        delete: operations["revokeAPIToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every account's balance as of a date.
         * @description Setting "currency" converts every account's balance into it, under "policy" - the response's "balances[].converted" carries the converted figure and its full provenance, and any account the conversion couldn't cover is reported under "unconverted" rather than silently dropped.
         */
        get: operations["getBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balances/net-worth-over-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Total balance across every account, as a time series.
         * @description The total balance across every account, converted into "currency" under "policy", at each "granularity" period boundary within "from".."to" (both required - there's no sensible default range for a time series). Every filter dimension other than "from"/"to" is ignored: net worth is a whole-ledger figure, not scoped to one account or category. Any account some period's conversion couldn't cover is reported once under "unconverted", not once per period.
         */
        get: operations["getNetWorthOverTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balances/totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Totals overview: overall net balance, per category, per currency.
         * @description The overall net balance and the per-category breakdown are converted into "currency" under "policy" - left unset, "currency" resolves to the actor's own reporting-currency preference, falling back to the instance default. The per-currency breakdown is always raw and unconverted. Any account the conversion couldn't cover is reported under "unconverted" rather than silently dropped or excluded without explanation.
         */
        get: operations["getBalanceTotals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every category, flat. */
        get: operations["listCategories"];
        put?: never;
        /** Create a category. */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one category by ID or unique name. */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /**
         * Archive a category.
         * @description This hides the category from pickers; transactions that already reference it remain valid.
         */
        delete: operations["archiveCategory"];
        options?: never;
        head?: never;
        /**
         * Rename a category, or move it to a new parent.
         * @description The request body must set exactly one of "name" or "parent" (an empty "parent" moves the category to top-level) - these are two separate operations at the application layer, and a request naming both or neither is rejected.
         */
        patch: operations["patchCategory"];
        trace?: never;
    };
    "/api/v1/fx/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up the exchange rate between two currencies.
         * @description A pure read over already-stored rates - this never calls out to the configured FX provider (use POST /api/v1/fx/rates/fetch for that). Setting "amount" also returns the converted figure.
         */
        get: operations["listFxRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fx/rates/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch and store exchange rates from the configured provider.
         * @description With no "pairs", fetches every currency pair actually in use across the actor's accounts and transactions, quoted against their reporting currency, at today's date. Pass "pairs" to restrict the fetch to specific base currencies, and "from"/"to" together for a historical backfill instead of just today.
         */
        post: operations["fetchFxRates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reporting-currency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** See the acting user's configured reporting currency. */
        get: operations["getReportingCurrency"];
        put?: never;
        /** Set the acting user's reporting currency. */
        post: operations["setReportingCurrency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions, newest first, with an optional filter. */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Record an outflow or an inflow.
         * @description For a transfer between two of the actor's own accounts, use POST /api/v1/transfers instead. When "date" is omitted, the server books the transaction to today in the actor's own timezone - never the client's.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one transaction by ID. */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /**
         * Delete a transaction.
         * @description The transaction stops appearing in lists and balances, but its history is retained.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /**
         * Replace a transaction's editable fields.
         * @description This is a full replacement of every field in the request body, not a partial patch: send every field's current value, not only the one that's changing. A transaction's type (outflow, inflow, transfer) can't change.
         */
        patch: operations["editTransaction"];
        trace?: never;
    };
    "/api/v1/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move money between two of the actor's own accounts.
         * @description A transfer between accounts in different currencies is allowed: the implied exchange rate between the two legs is derived and recorded automatically, from "to_amount" when given or from "amount"'s raw digits reinterpreted in the to-currency otherwise.
         */
        post: operations["createTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report that the server is running. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            archived: boolean;
            /**
             * Format: date
             * @description Set only once the account is archived.
             */
            archived_at?: string;
            currency: string;
            id: string;
            institution?: string;
            name: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            opening_balance: string;
            /**
             * Format: date
             * @description The date the opening balance is stated as of.
             */
            opening_balance_date?: string;
            /** @description Where the account sorts in a list; lower comes first. */
            sort_order: number;
            /** @enum {string} */
            type: "bank" | "cash" | "credit_card" | "wallet" | "investment" | "loan" | "other";
        };
        AccountEnvelope: {
            data: components["schemas"]["Account"];
        };
        AccountKindTotal: {
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            /** @enum {string} */
            kind: "bank" | "cash" | "credit_card" | "wallet" | "investment" | "loan" | "other";
        };
        AccountListEnvelope: {
            data: components["schemas"]["Account"][];
        };
        ApiToken: {
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Absent for a token that doesn't expire.
             */
            expires_at?: string;
            id: string;
            /**
             * Format: date-time
             * @description Absent if the token has never been used.
             */
            last_used_at?: string;
            name: string;
            /**
             * Format: date-time
             * @description Absent for a token that's still live.
             */
            revoked_at?: string;
        };
        ApiTokenListEnvelope: {
            data: components["schemas"]["ApiToken"][];
        };
        Auth: {
            actor_id: string;
        };
        AuthEnvelope: {
            data: components["schemas"]["Auth"];
        };
        AverageTransactionSize: {
            by_category: components["schemas"]["AverageTransactionSizeRow"][];
            currency: string;
            overall: components["schemas"]["AverageTransactionSizeRow"];
            unconverted?: components["schemas"]["UnconvertedPosting"][];
        };
        AverageTransactionSizeEnvelope: {
            data: components["schemas"]["AverageTransactionSize"];
        };
        AverageTransactionSizeRow: {
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            average: string;
            category: string;
            count: number;
        };
        Balance: {
            /** @description The account's name. */
            account: string;
            account_id: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            converted?: components["schemas"]["ConvertedBalance"];
            currency: string;
        };
        BalanceTotals: {
            /**
             * Format: date
             * @description The date every total below is computed as of.
             */
            as_of: string;
            by_category: components["schemas"]["AccountKindTotal"][];
            by_currency: components["schemas"]["CurrencyTotal"][];
            /** @description The reporting currency "overall" and "by_category" are expressed in. */
            currency: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            overall: string;
            unconverted?: components["schemas"]["UnconvertedBalance"][];
        };
        BalanceTotalsEnvelope: {
            data: components["schemas"]["BalanceTotals"];
        };
        Balances: {
            /**
             * Format: date
             * @description The date every balance below is computed as of.
             */
            as_of: string;
            balances: components["schemas"]["Balance"][];
            unconverted?: components["schemas"]["UnconvertedBalance"][];
        };
        BalancesEnvelope: {
            data: components["schemas"]["Balances"];
        };
        CashFlow: {
            currency: string;
            points: components["schemas"]["CashFlowPoint"][];
            unconverted?: components["schemas"]["UnconvertedPosting"][];
        };
        CashFlowEnvelope: {
            data: components["schemas"]["CashFlow"];
        };
        CashFlowPoint: {
            /** Format: date */
            from: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            inflow: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            net: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            outflow: string;
            /** Format: date */
            to: string;
        };
        Category: {
            archived: boolean;
            /**
             * Format: date
             * @description Set only once the category is archived.
             */
            archived_at?: string;
            id: string;
            name: string;
            /** @description Absent for a top-level category. */
            parent_id?: string;
            /** @description Where the category sorts in a list; lower comes first. */
            sort_order: number;
            /** @enum {string} */
            type: "expense" | "income";
        };
        CategoryBreakdown: {
            currency: string;
            rows: components["schemas"]["CategoryBreakdownRow"][];
            unconverted?: components["schemas"]["UnconvertedPosting"][];
        };
        CategoryBreakdownEnvelope: {
            data: components["schemas"]["CategoryBreakdown"];
        };
        CategoryBreakdownRow: {
            category: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            income: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            net: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            spending: string;
        };
        CategoryEnvelope: {
            data: components["schemas"]["Category"];
        };
        CategoryListEnvelope: {
            data: components["schemas"]["Category"][];
        };
        CategoryTrendDelta: {
            category: string;
            current: components["schemas"]["CategoryBreakdownRow"];
            /** Format: double */
            income_change_pct?: number | null;
            previous: components["schemas"]["CategoryBreakdownRow"];
            /** Format: double */
            spending_change_pct?: number | null;
        };
        CategoryTrends: {
            currency: string;
            /** Format: date */
            current_from: string;
            /** Format: date */
            current_to: string;
            /** Format: date */
            previous_from: string;
            /** Format: date */
            previous_to: string;
            rows: components["schemas"]["CategoryTrendDelta"][];
            unconverted?: components["schemas"]["UnconvertedPosting"][];
        };
        CategoryTrendsEnvelope: {
            data: components["schemas"]["CategoryTrends"];
        };
        ChangePasswordRequest: {
            new_password: string;
        };
        ConvertedBalance: {
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            currency: string;
            /** @enum {string} */
            policy: "transaction_date" | "current" | "pinned";
            rate: string;
            /** Format: date */
            rate_date: string;
            rate_source: string;
            stale: boolean;
        };
        CreateAPITokenRequest: {
            /**
             * Format: date
             * @description Omit for a token that never expires.
             */
            expires_at?: string;
            name: string;
        };
        CreateAPITokenResponse: {
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Absent for a token that doesn't expire.
             */
            expires_at?: string;
            id: string;
            name: string;
            /** @description The plaintext token. Shown only this once - store it now; it can't be retrieved again. */
            token: string;
        };
        CreateAPITokenResponseEnvelope: {
            data: components["schemas"]["CreateAPITokenResponse"];
        };
        CreateAccountRequest: {
            currency?: string;
            institution?: string;
            name: string;
            /**
             * Format: money
             * @description Defaults to zero.
             */
            opening_balance?: string;
            /**
             * Format: date
             * @description The date the opening balance is stated as of. Omit to state it as of today.
             */
            opening_balance_date?: string;
            /** @description Where the account sorts in a list; lower comes first. */
            sort_order?: number;
            /** @enum {string} */
            type: "bank" | "cash" | "credit_card" | "wallet" | "investment" | "loan" | "other";
        };
        CreateCategoryRequest: {
            name: string;
            /** @description A parent category's ID or unique name. Omit for a top-level category. */
            parent?: string;
            /** @description Where the category sorts in a list; lower comes first. */
            sort_order?: number;
            /** @enum {string} */
            type: "expense" | "income";
        };
        CreateTransactionRequest: {
            /** @description An account's ID or unique name. */
            account: string;
            /**
             * Format: money
             * @description Always positive; type says which way the money moves.
             */
            amount: string;
            /** @description A category's ID or unique name. */
            category?: string;
            currency?: string;
            /**
             * Format: date
             * @description Omit to book the transaction to today in the account owner's own timezone.
             */
            date?: string;
            description: string;
            notes?: string;
            tags?: string[];
            /** @enum {string} */
            type: "outflow" | "inflow";
        };
        CreateTransferRequest: {
            /**
             * Format: money
             * @description Always positive, in the from-account's own currency.
             */
            amount: string;
            /**
             * Format: date
             * @description Omit to book the transfer to today in the account owner's own timezone.
             */
            date?: string;
            description: string;
            /** @description An account's ID or unique name: the account the money leaves. */
            from_account: string;
            notes?: string;
            tags?: string[];
            /** @description An account's ID or unique name: the account the money arrives in. */
            to_account: string;
            /**
             * Format: money
             * @description The to-leg's own amount, in the to-account's own currency. Omit to reuse amount's raw digits, reinterpreted in the to-currency, as before. Set this to record a real cross-currency exchange rate rather than an accidental 1:1.
             */
            to_amount?: string;
        };
        CurrencyTotal: {
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            currency: string;
        };
        EditTransactionRequest: {
            /** @description An account's ID or unique name. Read when editing an outflow or an inflow. */
            account?: string;
            /**
             * Format: money
             * @description Always positive; the transaction's own type says which way the money moves.
             */
            amount: string;
            /** @description A category's ID or unique name. Read when editing an outflow or an inflow. */
            category?: string;
            currency?: string;
            /**
             * Format: date
             * @description Omit to book the transaction to today in the account owner's own timezone.
             */
            date?: string;
            description: string;
            /** @description An account's ID or unique name. Read when editing a transfer. */
            from_account?: string;
            notes?: string;
            tags?: string[];
            /** @description An account's ID or unique name. Read when editing a transfer. */
            to_account?: string;
            /**
             * Format: money
             * @description The to-leg's own amount, in the to-account's own currency. Read when editing a transfer; omit to reuse amount's raw digits, reinterpreted in the to-currency, as before.
             */
            to_amount?: string;
        };
        Error: {
            /** @enum {string} */
            code: "conflict" | "internal" | "invalid_input" | "not_allowed" | "not_found" | "precondition_failed" | "unauthenticated" | "unavailable";
            /** @description Safe, structured extra context - candidate names, valid options. */
            details?: {
                [key: string]: unknown;
            };
            /** @description The request field or CLI flag this error attaches to, when there is one. */
            field?: string;
            message: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        FetchFxRatesRequest: {
            /**
             * Format: date
             * @description Backfill range start date, inclusive (requires "to").
             */
            from?: string;
            /** @description Restrict the fetch to these base currencies. Omit to fetch every in-use pair (quote is ignored in that case). */
            pairs?: string[];
            /** @description Quote currency for every pairs entry, instead of the resolved reporting currency. Ignored when pairs is omitted. */
            quote?: string;
            /**
             * Format: date
             * @description Backfill range end date, inclusive (requires "from").
             */
            to?: string;
        };
        FetchedRate: {
            /** Format: date */
            date: string;
            /** @description The currency pair fetched, as "<base>/<quote>". */
            pair: string;
            rate: string;
            source: string;
        };
        FxFetch: {
            fetched: components["schemas"]["FetchedRate"][];
            reporting_currency: string;
        };
        FxFetchEnvelope: {
            data: components["schemas"]["FxFetch"];
        };
        FxRate: {
            /** @description The requested amount, in the from currency. Set only when "amount" was given. */
            amount?: string;
            /** @description The converted figure, in the to currency. Set only when "amount" was given. */
            converted?: string;
            from: string;
            /** @enum {string} */
            policy: "transaction_date" | "current" | "pinned";
            rate: string;
            /** Format: date */
            rate_date: string;
            rate_source: string;
            stale: boolean;
            to: string;
        };
        FxRateEnvelope: {
            data: components["schemas"]["FxRate"];
        };
        Healthz: {
            /** @enum {string} */
            status: "ok";
        };
        HealthzEnvelope: {
            data: components["schemas"]["Healthz"];
        };
        LoginRequest: {
            password: string;
        };
        NetWorthOverTime: {
            currency: string;
            points: components["schemas"]["NetWorthPoint"][];
            unconverted?: components["schemas"]["UnconvertedBalance"][];
        };
        NetWorthOverTimeEnvelope: {
            data: components["schemas"]["NetWorthOverTime"];
        };
        NetWorthPoint: {
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            /** Format: date */
            date: string;
        };
        Ok: {
            ok: boolean;
        };
        OkEnvelope: {
            data: components["schemas"]["Ok"];
        };
        PatchAccountRequest: {
            /** @description The account's new name. */
            name?: string | null;
            /**
             * Format: money
             * @description The opening balance to re-declare.
             */
            opening_balance?: string | null;
            /**
             * Format: date
             * @description The date the new opening balance is stated as of. Only read alongside opening_balance.
             */
            opening_balance_date?: string | null;
        };
        PatchCategoryRequest: {
            /** @description The category's new name. */
            name?: string | null;
            /** @description A parent category's ID or unique name. An empty string moves the category to the top level. */
            parent?: string | null;
        };
        ReportingCurrency: {
            currency: string;
            /** @description The effective reporting currency for this actor; either the actor-set value or the instance default if none is set. */
            effectiveCurrency: string;
            /** @description False when this actor has never set a reporting currency; the instance default is used instead. */
            is_set: boolean;
        };
        ReportingCurrencyEnvelope: {
            data: components["schemas"]["ReportingCurrency"];
        };
        SavingsRate: {
            currency: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            income: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            net: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            outflow: string;
            /** Format: double */
            rate?: number | null;
            unconverted?: components["schemas"]["UnconvertedPosting"][];
        };
        SavingsRateEnvelope: {
            data: components["schemas"]["SavingsRate"];
        };
        SetReportingCurrencyRequest: {
            currency: string;
        };
        TopTransactions: {
            currency: string;
            rows: components["schemas"]["TopTransactionsRow"][];
            unconverted?: components["schemas"]["UnconvertedPosting"][];
        };
        TopTransactionsEnvelope: {
            data: components["schemas"]["TopTransactions"];
        };
        TopTransactionsRow: {
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            category: string;
            /** Format: date */
            date: string;
            description: string;
            transaction_id: string;
        };
        Transaction: {
            /** @description Set on an outflow or an inflow. */
            account_id?: string;
            /**
             * Format: money
             * @description Always positive. For an outflow or inflow, that entry's own amount. For a transfer, the from-leg's own amount — the same value PATCHing this transaction's own "amount" field back unchanged expects.
             */
            amount: string;
            /** @description Set on an outflow or an inflow that has a category. */
            category_id?: string;
            currency: string;
            /**
             * Format: date
             * @description The date the transaction is booked to.
             */
            date: string;
            description: string;
            /** @description Set on a transfer: the account the money left. */
            from_account_id?: string;
            id: string;
            notes?: string;
            /** @description A transfer's implied exchange rate, "1 <from currency> = <value> <to currency>". Set only for a cross-currency transfer. */
            rate?: string;
            rate_source?: string;
            tags?: string[];
            /** @description Set on a transfer: the account the money arrived in. */
            to_account_id?: string;
            /**
             * Format: money
             * @description Set only on a transfer: the to-leg's own amount, in the to-account's own currency — the same value PATCHing this transaction's own "to_amount" field back unchanged expects.
             */
            to_amount?: string;
            /** @description Set only on a transfer: the to-leg's own currency. */
            to_currency?: string;
            /** @enum {string} */
            type: "outflow" | "inflow" | "transfer";
        };
        TransactionEnvelope: {
            data: components["schemas"]["Transaction"];
        };
        TransactionList: {
            data: components["schemas"]["Transaction"][];
            /** @description An opaque token for the next page. Present only when there is a next page; its encoding isn't part of the API's contract and may change. */
            next_cursor?: string;
        };
        TransactionListEnvelope: {
            data: components["schemas"]["TransactionList"];
        };
        TrendPeriod: {
            /** Format: date */
            from: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            inflow: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            net: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            outflow: string;
            /** Format: date */
            to: string;
        };
        Trends: {
            currency: string;
            current: components["schemas"]["TrendPeriod"];
            /** Format: double */
            inflow_change_pct?: number | null;
            /** Format: double */
            outflow_change_pct?: number | null;
            previous: components["schemas"]["TrendPeriod"];
            unconverted?: components["schemas"]["UnconvertedPosting"][];
        };
        TrendsEnvelope: {
            data: components["schemas"]["Trends"];
        };
        UnconvertedBalance: {
            account: string;
            reason: string;
        };
        UnconvertedPosting: {
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            currency: string;
            reason: string;
            transaction_id: string;
        };
    };
    responses: {
        /** @description The request failed validation. */
        InvalidInput: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No valid credential was presented. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description The resource's ID, or (for an account or category) its unique name. */
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every account, in name order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListEnvelope"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description The created account. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAccountRequest"];
            };
        };
        responses: {
            /** @description The updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    getAverageTransactionSize: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer" - a transfer never contributes to an analytics result (transfers are excluded by construction), so filtering to "transfer" alone always returns an empty result. */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                from?: string;
                /** @description The inclusive end of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                to?: string;
                /** @description Only include this transaction currency (repeatable). */
                filter_currency?: string;
                /** @description Only include transactions at or above this amount (absolute value). */
                amount_min?: string;
                /** @description Only include transactions at or below this amount (absolute value). */
                amount_max?: string;
                /** @description Only include transactions whose description contains this text. */
                description?: string;
                /** @description Only include transactions carrying this tag (repeatable). */
                tag?: string;
                /** @description How multiple "tag" values combine. */
                tag_mode?: "any" | "all";
                /** @description Convert every figure in the result into this currency (required). */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The overall and per-category mean transaction size. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AverageTransactionSizeEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getCashFlow: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer" - a transfer never contributes to an analytics result (transfers are excluded by construction), so filtering to "transfer" alone always returns an empty result. */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                from?: string;
                /** @description The inclusive end of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                to?: string;
                /** @description Only include this transaction currency (repeatable). */
                filter_currency?: string;
                /** @description Only include transactions at or above this amount (absolute value). */
                amount_min?: string;
                /** @description Only include transactions at or below this amount (absolute value). */
                amount_max?: string;
                /** @description Only include transactions whose description contains this text. */
                description?: string;
                /** @description Only include transactions carrying this tag (repeatable). */
                tag?: string;
                /** @description How multiple "tag" values combine. */
                tag_mode?: "any" | "all";
                /** @description Convert every figure in the result into this currency (required). */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
                /** @description How to bucket/compare periods. Defaults to "month". */
                granularity?: "week" | "month" | "year" | "custom";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One point per period, ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashFlowEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getCategoryBreakdown: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer" - a transfer never contributes to an analytics result (transfers are excluded by construction), so filtering to "transfer" alone always returns an empty result. */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                from?: string;
                /** @description The inclusive end of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                to?: string;
                /** @description Only include this transaction currency (repeatable). */
                filter_currency?: string;
                /** @description Only include transactions at or above this amount (absolute value). */
                amount_min?: string;
                /** @description Only include transactions at or below this amount (absolute value). */
                amount_max?: string;
                /** @description Only include transactions whose description contains this text. */
                description?: string;
                /** @description Only include transactions carrying this tag (repeatable). */
                tag?: string;
                /** @description How multiple "tag" values combine. */
                tag_mode?: "any" | "all";
                /** @description Convert every figure in the result into this currency (required). */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per top-level category with at least one matching posting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryBreakdownEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getCategoryTrends: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer" - a transfer never contributes to an analytics result (transfers are excluded by construction), so filtering to "transfer" alone always returns an empty result. */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                from?: string;
                /** @description The inclusive end of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                to?: string;
                /** @description Only include this transaction currency (repeatable). */
                filter_currency?: string;
                /** @description Only include transactions at or above this amount (absolute value). */
                amount_min?: string;
                /** @description Only include transactions at or below this amount (absolute value). */
                amount_max?: string;
                /** @description Only include transactions whose description contains this text. */
                description?: string;
                /** @description Only include transactions carrying this tag (repeatable). */
                tag?: string;
                /** @description How multiple "tag" values combine. */
                tag_mode?: "any" | "all";
                /** @description Convert every figure in the result into this currency (required). */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
                /** @description How to bucket/compare periods. Defaults to "month". */
                granularity?: "week" | "month" | "year" | "custom";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resolved current/previous period bounds and one row per top-level category present in either period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryTrendsEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getSavingsRate: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer" - a transfer never contributes to an analytics result (transfers are excluded by construction), so filtering to "transfer" alone always returns an empty result. */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                from?: string;
                /** @description The inclusive end of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                to?: string;
                /** @description Only include this transaction currency (repeatable). */
                filter_currency?: string;
                /** @description Only include transactions at or above this amount (absolute value). */
                amount_min?: string;
                /** @description Only include transactions at or below this amount (absolute value). */
                amount_max?: string;
                /** @description Only include transactions whose description contains this text. */
                description?: string;
                /** @description Only include transactions carrying this tag (repeatable). */
                tag?: string;
                /** @description How multiple "tag" values combine. */
                tag_mode?: "any" | "all";
                /** @description Convert every figure in the result into this currency (required). */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Income, outflow, net, and the savings rate over the resolved filter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsRateEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getTopTransactions: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer" - a transfer never contributes to an analytics result (transfers are excluded by construction), so filtering to "transfer" alone always returns an empty result. */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                from?: string;
                /** @description The inclusive end of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                to?: string;
                /** @description Only include this transaction currency (repeatable). */
                filter_currency?: string;
                /** @description Only include transactions at or above this amount (absolute value). */
                amount_min?: string;
                /** @description Only include transactions at or below this amount (absolute value). */
                amount_max?: string;
                /** @description Only include transactions whose description contains this text. */
                description?: string;
                /** @description Only include transactions carrying this tag (repeatable). */
                tag?: string;
                /** @description How multiple "tag" values combine. */
                tag_mode?: "any" | "all";
                /** @description Convert every figure in the result into this currency (required). */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
                /** @description The top-N count. Defaults to 10, capped at 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The largest matching transactions, descending by absolute amount. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopTransactionsEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getTrends: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer" - a transfer never contributes to an analytics result (transfers are excluded by construction), so filtering to "transfer" alone always returns an empty result. */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                from?: string;
                /** @description The inclusive end of a booked-date range. Ignored by /trends except when its own granularity is "custom". */
                to?: string;
                /** @description Only include this transaction currency (repeatable). */
                filter_currency?: string;
                /** @description Only include transactions at or above this amount (absolute value). */
                amount_min?: string;
                /** @description Only include transactions at or below this amount (absolute value). */
                amount_max?: string;
                /** @description Only include transactions whose description contains this text. */
                description?: string;
                /** @description Only include transactions carrying this tag (repeatable). */
                tag?: string;
                /** @description How multiple "tag" values combine. */
                tag_mode?: "any" | "all";
                /** @description Convert every figure in the result into this currency (required). */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
                /** @description How to bucket/compare periods. Defaults to "month". */
                granularity?: "week" | "month" | "year" | "custom";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current and previous period's totals, plus each one's percentage change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    logoutAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The password was changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    listAPITokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every API token, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenListEnvelope"];
                };
            };
        };
    };
    createAPIToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPITokenRequest"];
            };
        };
        responses: {
            /** @description The created token, including its one-time plaintext value. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAPITokenResponseEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    revokeAPIToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The token was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBalances: {
        parameters: {
            query?: {
                /** @description Defaults to today in the actor's own timezone when omitted. */
                as_of?: string;
                /** @description Convert every account's balance into this currency. */
                currency?: string;
                /** @description Which conversion policy to use when "currency" is set. */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned" and "currency" is set). */
                pinned_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every account's balance as of the resolved date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getNetWorthOverTime: {
        parameters: {
            query?: {
                /** @description The inclusive start of the range (required). */
                from?: string;
                /** @description The inclusive end of the range (required). */
                to?: string;
                /** @description Convert every point into this currency. Defaults to the actor's own reporting currency. */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
                /** @description How to bucket/compare periods. Defaults to "month". */
                granularity?: "week" | "month" | "year" | "custom";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One point per period boundary in the requested range, ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthOverTimeEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getBalanceTotals: {
        parameters: {
            query?: {
                /** @description Defaults to today in the actor's own timezone when omitted. */
                as_of?: string;
                /** @description Convert the overall and per-category totals into this currency. Defaults to the actor's own reporting currency. */
                currency?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The pinned date to convert at (required when "policy" is "pinned"). */
                pinned_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The totals overview as of the resolved date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceTotalsEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListEnvelope"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description The created category. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchCategoryRequest"];
            };
        };
        responses: {
            /** @description The updated category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    listFxRates: {
        parameters: {
            query?: {
                /** @description The currency to look up a rate for (required). */
                from?: string;
                /** @description The currency it's quoted against (required). */
                to?: string;
                /** @description Which conversion policy to use (required). */
                policy?: "transaction_date" | "current" | "pinned";
                /** @description The transaction date to look the rate up at (required with policy=transaction_date). */
                transaction_date?: string;
                /** @description The pinned date to look the rate up at (required with policy=pinned). */
                pinned_date?: string;
                /** @description An amount in "from"'s currency to convert (optional). */
                amount?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resolved rate and (when "amount" was set) the converted figure. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxRateEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    fetchFxRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchFxRatesRequest"];
            };
        };
        responses: {
            /** @description Every rate fetched and stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxFetchEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    getReportingCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configured reporting currency, or that none is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportingCurrencyEnvelope"];
                };
            };
        };
    };
    setReportingCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetReportingCurrencyRequest"];
            };
        };
        responses: {
            /** @description The reporting currency was set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer". */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. */
                from?: string;
                /** @description The inclusive end of a booked-date range. */
                to?: string;
                /** @description Page size; defaults to 50 and caps at 200. */
                limit?: number;
                /** @description An opaque token from a previous page's "next_cursor". Its encoding is not part of the API's contract and may change. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matching transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description The recorded transaction. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deleted transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    editTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditTransactionRequest"];
            };
        };
        responses: {
            /** @description The updated transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    createTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description The recorded transfer. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzEnvelope"];
                };
            };
        };
    };
}
