/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every account. */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account. */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one account by ID or unique name. */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        /**
         * Archive an account.
         * @description This hides the account from pickers; its history remains. There is no hard delete for an account with any history.
         */
        delete: operations["archiveAccount"];
        options?: never;
        head?: never;
        /**
         * Rename an account, or re-declare its opening balance.
         * @description The request body must set exactly one of "name" or "opening_balance" - these are two separate operations at the application layer, and a request naming both or neither is rejected.
         */
        patch: operations["patchAccount"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in and start a session.
         * @description On success, sets an HttpOnly session cookie the browser holds and resends automatically - the response body carries no credential to store.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session.
         * @description Requires a session cookie; a bearer-token request has no session to end - revoke the API token instead.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End every session the acting user has open.
         * @description Revokes every session, including the one that made this request, if any.
         */
        post: operations["logoutAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the acting user's password.
         * @description Revokes every session the acting user has open, including whichever one made this request - it will need to sign in again afterward.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every API token the acting user owns.
         * @description Includes revoked and expired tokens, for history - not only what's currently live.
         */
        get: operations["listAPITokens"];
        put?: never;
        /**
         * Issue a new API token.
         * @description The plaintext token is returned exactly once, in this response - it can't be retrieved again.
         */
        post: operations["createAPIToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API token.
         * @description The token stops authenticating immediately, but remains listed (soft revocation).
         */
        delete: operations["revokeAPIToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every account's balance as of a date. */
        get: operations["getBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every category, flat. */
        get: operations["listCategories"];
        put?: never;
        /** Create a category. */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one category by ID or unique name. */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        /**
         * Archive a category.
         * @description This hides the category from pickers; transactions that already reference it remain valid.
         */
        delete: operations["archiveCategory"];
        options?: never;
        head?: never;
        /**
         * Rename a category, or move it to a new parent.
         * @description The request body must set exactly one of "name" or "parent" (an empty "parent" moves the category to top-level) - these are two separate operations at the application layer, and a request naming both or neither is rejected.
         */
        patch: operations["patchCategory"];
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions, newest first, with an optional filter. */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Record an outflow or an inflow.
         * @description For a transfer between two of the actor's own accounts, use POST /api/v1/transfers instead. When "date" is omitted, the server books the transaction to today in the actor's own timezone - never the client's.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one transaction by ID. */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /**
         * Delete a transaction.
         * @description The transaction stops appearing in lists and balances, but its history is retained.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /**
         * Replace a transaction's editable fields.
         * @description This is a full replacement of every field in the request body, not a partial patch: send every field's current value, not only the one that's changing. A transaction's type (outflow, inflow, transfer) can't change.
         */
        patch: operations["editTransaction"];
        trace?: never;
    };
    "/api/v1/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move money between two of the actor's own accounts.
         * @description A transfer between accounts in different currencies is allowed: the implied exchange rate between the two legs is derived and recorded automatically.
         */
        post: operations["createTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report that the server is running. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            archived: boolean;
            /**
             * Format: date
             * @description Set only once the account is archived.
             */
            archived_at?: string;
            currency: string;
            id: string;
            institution?: string;
            name: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            opening_balance: string;
            /**
             * Format: date
             * @description The date the opening balance is stated as of.
             */
            opening_balance_date?: string;
            /** @description Where the account sorts in a list; lower comes first. */
            sort_order: number;
            /** @enum {string} */
            type: "bank" | "cash" | "credit_card" | "wallet" | "investment" | "loan" | "other";
        };
        AccountEnvelope: {
            data: components["schemas"]["Account"];
        };
        AccountListEnvelope: {
            data: components["schemas"]["Account"][];
        };
        ApiToken: {
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Absent for a token that doesn't expire.
             */
            expires_at?: string;
            id: string;
            /**
             * Format: date-time
             * @description Absent if the token has never been used.
             */
            last_used_at?: string;
            name: string;
            /**
             * Format: date-time
             * @description Absent for a token that's still live.
             */
            revoked_at?: string;
        };
        ApiTokenListEnvelope: {
            data: components["schemas"]["ApiToken"][];
        };
        Auth: {
            actor_id: string;
        };
        AuthEnvelope: {
            data: components["schemas"]["Auth"];
        };
        Balance: {
            /** @description The account's name. */
            account: string;
            account_id: string;
            /**
             * Format: money
             * @description A plain decimal amount. Always a JSON string, in the sibling currency field's currency - never a number.
             */
            amount: string;
            currency: string;
        };
        Balances: {
            /**
             * Format: date
             * @description The date every balance below is computed as of.
             */
            as_of: string;
            balances: components["schemas"]["Balance"][];
        };
        BalancesEnvelope: {
            data: components["schemas"]["Balances"];
        };
        Category: {
            archived: boolean;
            /**
             * Format: date
             * @description Set only once the category is archived.
             */
            archived_at?: string;
            id: string;
            name: string;
            /** @description Absent for a top-level category. */
            parent_id?: string;
            /** @description Where the category sorts in a list; lower comes first. */
            sort_order: number;
            /** @enum {string} */
            type: "expense" | "income";
        };
        CategoryEnvelope: {
            data: components["schemas"]["Category"];
        };
        CategoryListEnvelope: {
            data: components["schemas"]["Category"][];
        };
        ChangePasswordRequest: {
            new_password: string;
        };
        CreateAPITokenRequest: {
            /**
             * Format: date
             * @description Omit for a token that never expires.
             */
            expires_at?: string;
            name: string;
        };
        CreateAPITokenResponse: {
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Absent for a token that doesn't expire.
             */
            expires_at?: string;
            id: string;
            name: string;
            /** @description The plaintext token. Shown only this once - store it now; it can't be retrieved again. */
            token: string;
        };
        CreateAPITokenResponseEnvelope: {
            data: components["schemas"]["CreateAPITokenResponse"];
        };
        CreateAccountRequest: {
            currency?: string;
            institution?: string;
            name: string;
            /**
             * Format: money
             * @description Defaults to zero.
             */
            opening_balance?: string;
            /**
             * Format: date
             * @description The date the opening balance is stated as of. Omit to state it as of today.
             */
            opening_balance_date?: string;
            /** @description Where the account sorts in a list; lower comes first. */
            sort_order?: number;
            /** @enum {string} */
            type: "bank" | "cash" | "credit_card" | "wallet" | "investment" | "loan" | "other";
        };
        CreateCategoryRequest: {
            name: string;
            /** @description A parent category's ID or unique name. Omit for a top-level category. */
            parent?: string;
            /** @description Where the category sorts in a list; lower comes first. */
            sort_order?: number;
            /** @enum {string} */
            type: "expense" | "income";
        };
        CreateTransactionRequest: {
            /** @description An account's ID or unique name. */
            account: string;
            /**
             * Format: money
             * @description Always positive; type says which way the money moves.
             */
            amount: string;
            /** @description A category's ID or unique name. */
            category?: string;
            currency?: string;
            /**
             * Format: date
             * @description Omit to book the transaction to today in the account owner's own timezone.
             */
            date?: string;
            description: string;
            notes?: string;
            tags?: string[];
            /** @enum {string} */
            type: "outflow" | "inflow";
        };
        CreateTransferRequest: {
            /**
             * Format: money
             * @description Always positive, in the from-account's own currency.
             */
            amount: string;
            /**
             * Format: date
             * @description Omit to book the transfer to today in the account owner's own timezone.
             */
            date?: string;
            description: string;
            /** @description An account's ID or unique name: the account the money leaves. */
            from_account: string;
            notes?: string;
            tags?: string[];
            /** @description An account's ID or unique name: the account the money arrives in. */
            to_account: string;
        };
        EditTransactionRequest: {
            /** @description An account's ID or unique name. Read when editing an outflow or an inflow. */
            account?: string;
            /**
             * Format: money
             * @description Always positive; the transaction's own type says which way the money moves.
             */
            amount: string;
            /** @description A category's ID or unique name. Read when editing an outflow or an inflow. */
            category?: string;
            currency?: string;
            /**
             * Format: date
             * @description Omit to book the transaction to today in the account owner's own timezone.
             */
            date?: string;
            description: string;
            /** @description An account's ID or unique name. Read when editing a transfer. */
            from_account?: string;
            notes?: string;
            tags?: string[];
            /** @description An account's ID or unique name. Read when editing a transfer. */
            to_account?: string;
        };
        Error: {
            /** @enum {string} */
            code: "conflict" | "internal" | "invalid_input" | "not_allowed" | "not_found" | "precondition_failed" | "unauthenticated" | "unavailable";
            /** @description Safe, structured extra context - candidate names, valid options. */
            details?: {
                [key: string]: unknown;
            };
            /** @description The request field or CLI flag this error attaches to, when there is one. */
            field?: string;
            message: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        Healthz: {
            /** @enum {string} */
            status: "ok";
        };
        HealthzEnvelope: {
            data: components["schemas"]["Healthz"];
        };
        LoginRequest: {
            password: string;
        };
        Ok: {
            ok: boolean;
        };
        OkEnvelope: {
            data: components["schemas"]["Ok"];
        };
        PatchAccountRequest: {
            /** @description The account's new name. */
            name?: string | null;
            /**
             * Format: money
             * @description The opening balance to re-declare.
             */
            opening_balance?: string | null;
            /**
             * Format: date
             * @description The date the new opening balance is stated as of. Only read alongside opening_balance.
             */
            opening_balance_date?: string | null;
        };
        PatchCategoryRequest: {
            /** @description The category's new name. */
            name?: string | null;
            /** @description A parent category's ID or unique name. An empty string moves the category to the top level. */
            parent?: string | null;
        };
        Transaction: {
            /** @description Set on an outflow or an inflow. */
            account_id?: string;
            /**
             * Format: money
             * @description Always positive; the transaction's type says which way the money moved.
             */
            amount: string;
            /** @description Set on an outflow or an inflow that has a category. */
            category_id?: string;
            currency: string;
            /**
             * Format: date
             * @description The date the transaction is booked to.
             */
            date: string;
            description: string;
            /** @description Set on a transfer: the account the money left. */
            from_account_id?: string;
            id: string;
            notes?: string;
            tags?: string[];
            /** @description Set on a transfer: the account the money arrived in. */
            to_account_id?: string;
            /** @enum {string} */
            type: "outflow" | "inflow" | "transfer";
        };
        TransactionEnvelope: {
            data: components["schemas"]["Transaction"];
        };
        TransactionList: {
            data: components["schemas"]["Transaction"][];
            /** @description An opaque token for the next page. Present only when there is a next page; its encoding isn't part of the API's contract and may change. */
            next_cursor?: string;
        };
        TransactionListEnvelope: {
            data: components["schemas"]["TransactionList"];
        };
    };
    responses: {
        /** @description The request failed validation. */
        InvalidInput: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No valid credential was presented. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description The resource's ID, or (for an account or category) its unique name. */
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every account, in name order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListEnvelope"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description The created account. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAccountRequest"];
            };
        };
        responses: {
            /** @description The updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    logoutAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The password was changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    listAPITokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every API token, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenListEnvelope"];
                };
            };
        };
    };
    createAPIToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPITokenRequest"];
            };
        };
        responses: {
            /** @description The created token, including its one-time plaintext value. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAPITokenResponseEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    revokeAPIToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The token was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBalances: {
        parameters: {
            query?: {
                /** @description Defaults to today in the actor's own timezone when omitted. */
                as_of?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every account's balance as of the resolved date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesEnvelope"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListEnvelope"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description The created category. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchCategoryRequest"];
            };
        };
        responses: {
            /** @description The updated category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                /** @description An account's ID or unique name. */
                account?: string;
                /** @description A category's ID or unique name; its whole subtree is included. */
                category?: string;
                /** @description One of "outflow", "inflow", or "transfer". */
                type?: "outflow" | "inflow" | "transfer";
                /** @description The inclusive start of a booked-date range. */
                from?: string;
                /** @description The inclusive end of a booked-date range. */
                to?: string;
                /** @description Page size; defaults to 50 and caps at 200. */
                limit?: number;
                /** @description An opaque token from a previous page's "next_cursor". Its encoding is not part of the API's contract and may change. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matching transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description The recorded transaction. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deleted transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    editTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The resource's ID, or (for an account or category) its unique name. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditTransactionRequest"];
            };
        };
        responses: {
            /** @description The updated transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidInput"];
        };
    };
    createTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description The recorded transfer. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionEnvelope"];
                };
            };
            422: components["responses"]["InvalidInput"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzEnvelope"];
                };
            };
        };
    };
}
