package ports

import (
	"context"
	"time"
)

// APIToken is a `bdg_`-prefixed API token's server-side record (ADR-0006):
// stored only as its hash, with a user-supplied name (since the plaintext
// is shown exactly once, at creation, and never again) and the timestamp
// bookkeeping the issue calls for. As with Session, nothing in this
// package or internal/adapters/sqlite decides CreatedAt, LastUsedAt,
// ExpiresAt, or RevokedAt — the application layer resolves those and
// passes them in already decided.
type APIToken struct {
	// ID identifies this token row, independent of the token itself —
	// generated by the application layer (internal/platform/idgen).
	ID string
	// UserID is the token's owner.
	UserID string
	// TokenHash is auth.HashAPIToken's hex-encoded SHA-256 of the
	// plaintext token the holder presents as a bearer token. The
	// plaintext itself is never persisted.
	TokenHash string
	// Name is the user-supplied label shown back to them when listing
	// their tokens ("laptop", "backup script").
	Name string
	// CreatedAt is when the token was issued.
	CreatedAt time.Time
	// LastUsedAt is when the token was last presented and accepted, or
	// nil if it has never been used.
	LastUsedAt *time.Time
	// ExpiresAt is the token's optional expiry (ADR-0006's credential
	// table: "optional expiry"), or nil for a token that doesn't expire.
	ExpiresAt *time.Time
	// RevokedAt is when the token was revoked, or nil if it is still
	// live. Unlike a Session, an API token is soft-revoked so it stays
	// listable — there is no Delete method here.
	RevokedAt *time.Time
}

// APITokenRepository persists API tokens (ADR-0006). Every method takes
// actorID and filters on it, except GetByTokenHash, which — like
// SessionRepository.GetByTokenHash — is the lookup that establishes who
// the actor is in the first place.
//
// Defined here, in the layer that consumes it (ADR-0007) —
// internal/adapters/sqlite implements it, and the application layer
// (issue #55) depends only on this interface.
type APITokenRepository interface {
	// Create persists a new token. It returns a *errs.Error with code
	// NotAllowed if token.UserID != actorID, and Conflict on a
	// TokenHash collision.
	Create(ctx context.Context, actorID string, token APIToken) error

	// GetByTokenHash returns the token whose TokenHash matches
	// tokenHash, regardless of owner. Returns a *errs.Error with code
	// NotFound if no such token exists. Callers are responsible for
	// checking RevokedAt and ExpiresAt themselves; this method does not
	// filter on them.
	GetByTokenHash(ctx context.Context, tokenHash string) (APIToken, error)

	// List returns every token actorID owns — revoked and expired ones
	// included, since a token management screen needs to show history,
	// not just what's currently live — sorted (created_at DESC, id DESC)
	// for a deterministic, newest-first listing.
	List(ctx context.Context, actorID string) ([]APIToken, error)

	// Touch updates the token identified by id, owned by actorID, to
	// record use: LastUsedAt is overwritten with the value given.
	// Returns a *errs.Error with code NotFound if no such token exists
	// for that actor.
	Touch(ctx context.Context, actorID, id string, lastUsedAt time.Time) error

	// Revoke marks the token identified by id, owned by actorID, as
	// revoked as of revokedAt. It does not delete the row — a revoked
	// token remains listable via List. Returns a *errs.Error with code
	// NotFound if no such token exists for that actor.
	Revoke(ctx context.Context, actorID, id string, revokedAt time.Time) error
}
