package ports

import (
	"context"
	"time"
)

// MCPToolTier classifies an MCP tool by what it's allowed to do
// (ADR-0013, docs/architecture.md §3's "What MCP tools may not do"):
// read (always allowed), write (allowed, audited), or destructive
// (requires explicit confirmation, disabled by default). It's declared
// here, alongside MCPToolCall, rather than in internal/surface/mcp,
// because every layer that touches an MCPToolCall — the app layer that
// records one, the sqlite adapter that persists one, and the mcp surface
// that classifies its own tools — needs the same vocabulary, and ports is
// the one package all three may import (internal/lint's import-graph
// check).
type MCPToolTier string

const (
	// MCPToolTierRead is a query or analytics tool. Always allowed, never
	// audited.
	MCPToolTierRead MCPToolTier = "read"
	// MCPToolTierWrite is a tool that creates or edits data. Allowed,
	// audited.
	MCPToolTierWrite MCPToolTier = "write"
	// MCPToolTierDestructive is a tool that deletes, bulk-edits, commits
	// an import, or rolls one back. Disabled unless the server was
	// started with --allow-destructive, and gated by the
	// confirmation-token protocol even when it is.
	MCPToolTierDestructive MCPToolTier = "destructive"
)

// MCPToolCall is one recorded write- or write-or-destructive-tier MCP
// tool invocation (ADR-0013). read-tier calls are never recorded — see
// migration 00015_add_mcp_tool_call.sql's doc comment.
type MCPToolCall struct {
	// ID identifies this row — generated by the application layer
	// (internal/platform/idgen), the same as every other entity ID in
	// this codebase.
	ID string
	// UserID is the actor the call was made as. bodger has no MCP
	// credential of its own (ADR-0006) — this is always
	// ports.SeededUserID today, carried as a real field anyway so a
	// future multi-user MCP server doesn't need a schema change to
	// attribute a call to whoever actually made it.
	UserID string
	// ToolName is the MCP tool's registered name ("whoami", eventually
	// "delete_transaction" and friends).
	ToolName string
	// Tier is the tool's declared tier at the time it was called.
	Tier MCPToolTier
	// Arguments is the redacted JSON the tool was called with —
	// internal/app.RecordMCPToolCall applies the redaction before this
	// ever reaches a repository, so no credential or token value is ever
	// persisted here.
	Arguments string
	// ConfirmationToken is the single-use token this call issued or
	// consumed, for a destructive-tier call that went through the
	// confirmation protocol. Nil for a write-tier call, and nil for a
	// destructive call's own first (issuing) leg unless the tool
	// implementation chooses to record the token it just issued.
	ConfirmationToken *string
	// Result is "ok", or one of internal/platform/errs's registry codes
	// naming a business-logic failure (ADR-0013's "Tool Execution
	// Errors" — reported via CallToolResult.IsError, never a raw Go
	// error).
	Result string
	// CalledAt is when the call was recorded, resolved once by the
	// application layer's injected clock (ADR-0005) — never read
	// independently here or by the mcp surface.
	CalledAt time.Time
}

// MCPToolCallRepository persists mcp_tool_call rows (ADR-0013). Every
// method takes actorID and filters on it, the same as every other
// repository in this package (ADR-0006).
//
// Defined here, in the layer that consumes it (ADR-0007) —
// internal/adapters/sqlite implements it, and the application layer
// depends only on this interface, never on the adapter.
type MCPToolCallRepository interface {
	// Create persists a new call record. It returns a *errs.Error with
	// code NotAllowed if call.UserID != actorID.
	Create(ctx context.Context, actorID string, call MCPToolCall) error

	// List returns actorID's own recorded calls, most recently called
	// first, capped at limit rows.
	List(ctx context.Context, actorID string, limit int) ([]MCPToolCall, error)
}
