package ports

import (
	"context"
	"time"
)

// Session is a web UI session cookie's server-side record (ADR-0006):
// an opaque random token, stored only as its hash, with the sliding-expiry
// bookkeeping the credential needs. Nothing in this package or
// internal/adapters/sqlite computes CreatedAt, LastUsedAt, or ExpiresAt —
// those are "now"-dependent values the application layer resolves
// (CLAUDE.md's normalise-once rule) and passes in already decided.
type Session struct {
	// ID identifies this session row, independent of the token itself —
	// generated by the application layer (internal/platform/idgen), like
	// every other primary key in this schema.
	ID string
	// UserID is the session's owner.
	UserID string
	// TokenHash is auth.HashSessionToken's hex-encoded SHA-256 of the
	// plaintext session token the browser holds in its cookie. The
	// plaintext itself is never persisted.
	TokenHash string
	// CreatedAt is when the session was issued (login).
	CreatedAt time.Time
	// LastUsedAt is when the session was last presented and accepted.
	// Touch updates this alongside ExpiresAt on every sliding-expiry
	// renewal.
	LastUsedAt time.Time
	// ExpiresAt is when the session stops being valid absent a renewal.
	// ADR-0006's sliding expiry means this moves forward on activity
	// rather than being fixed at creation.
	ExpiresAt time.Time
}

// SessionRepository persists web UI sessions (ADR-0006). Every method that
// can identify a session's owner up front takes actorID and enforces it
// (ADR-0006); GetByTokenHash is the one exception, because establishing who
// the actor even is is exactly what that lookup is for.
//
// Defined here, in the layer that consumes it (ADR-0007) —
// internal/adapters/sqlite implements it, and the application layer
// (issue #55) depends only on this interface.
type SessionRepository interface {
	// Create persists a new session. It returns a *errs.Error with code
	// NotAllowed if session.UserID != actorID, and Conflict on a
	// TokenHash collision (astronomically unlikely given the token's
	// entropy, but not a case to silently ignore).
	Create(ctx context.Context, actorID string, session Session) error

	// GetByTokenHash returns the session whose TokenHash matches
	// tokenHash, regardless of owner — this is the lookup that
	// authenticates a request, so the actor isn't known yet. Returns a
	// *errs.Error with code NotFound if no such session exists. Callers
	// are responsible for checking ExpiresAt themselves; this method
	// does not filter on it.
	GetByTokenHash(ctx context.Context, tokenHash string) (Session, error)

	// Touch updates the session identified by id, owned by actorID, to
	// record a renewal: LastUsedAt and ExpiresAt are overwritten with the
	// values given. Returns a *errs.Error with code NotFound if no such
	// session exists for that actor.
	Touch(ctx context.Context, actorID, id string, lastUsedAt, expiresAt time.Time) error

	// Delete removes the session identified by id, owned by actorID.
	// This is how a session is revoked (ADR-0006: "revocation is a
	// DELETE") — there is no soft-revoke flag for sessions, unlike
	// APITokenRepository.Revoke. Returns a *errs.Error with code
	// NotFound if no such session exists for that actor.
	Delete(ctx context.Context, actorID, id string) error
}
