package app

import (
	"context"
	"errors"
	"time"

	"github.com/anirudhgray/bodger/internal/app/normalize"
	"github.com/anirudhgray/bodger/internal/domain/recurring"
	"github.com/anirudhgray/bodger/internal/platform/errs"
)

const maxRuleDescriptionLen = 200

// RecurringRuleResult wraps the RecurringRule a create/update/archive/get
// use case produced or affected, plus the currency its AmountMinor is
// denominated in. RecurringRule itself deliberately carries no currency
// field (its own doc comment: "amountMinor is denominated in the rule's
// account's currency") — resolving that currency needs an account lookup,
// which only the app layer can do (ADR-0005), so it travels here instead,
// the same reason BudgetActualsResult carries its own Currency rather than
// leaving a surface to guess it. Added for issue #281's surface wiring:
// every surface renders a rule's amount as a decimal string (the same
// convention budgetLineView.Amount already follows via
// BudgetLineAmount), and none of them may resolve an account's currency
// themselves.
type RecurringRuleResult struct {
	Rule     recurring.RecurringRule
	Currency string
}

// RecurringScheduleInput is the frequency-generic shape every recurring-rule
// command carries for its schedule: exactly the fields ADR-0014's RRULE
// subset needs, with only the ones the declared Frequency actually uses
// populated (the rest are ignored by buildSchedule, the same "only the
// right subset is ever read" discipline the domain Schedule constructors
// themselves enforce for the fields they populate).
type RecurringScheduleInput struct {
	Frequency  string
	Interval   int
	Weekday    time.Weekday
	DayOfMonth int
	Month      time.Month
}

// CreateRecurringRuleCommand creates a new RecurringRule template — no
// occurrence is generated by this call (issue #278's job). AccountRef/
// CategoryRef are resolved the same actor-scoped way every other use case
// resolves one (resolveOwnedAccount/resolveOwnedCategory), which doubles as
// this command's authorisation check (ADR-0006). Amount is a raw string
// denominated in the resolved account's own currency — a rule has no
// currency of its own, the same single-source-of-truth shape
// budgeting.BudgetLine uses against its budget (ADR-0014). StartsOn
// defaults to today when empty, per normalize.DateOf's own convention;
// EndsOn is genuinely optional (empty means the rule runs indefinitely).
type CreateRecurringRuleCommand struct {
	ActorID     string
	AccountRef  string
	CategoryRef string
	Amount      string
	Description string
	Schedule    RecurringScheduleInput
	StartsOn    string
	EndsOn      string
}

// CreateRecurringRule implements the "create" use case in issue #277's
// recurring-rule-CRUD scope.
func (s *Service) CreateRecurringRule(ctx context.Context, cmd CreateRecurringRuleCommand) (RecurringRuleResult, error) {
	if err := requireActorID(cmd.ActorID); err != nil {
		return RecurringRuleResult{}, err
	}

	account, err := s.resolveOwnedAccount(ctx, cmd.ActorID, cmd.AccountRef)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "account_ref")
	}
	category, err := s.resolveOwnedCategory(ctx, cmd.ActorID, cmd.CategoryRef)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "category_ref")
	}

	amountMinor, err := normalize.Amount(cmd.Amount, account.Currency())
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "amount")
	}

	description, err := normalize.Text(cmd.Description, maxRuleDescriptionLen)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "description")
	}
	if description == "" {
		return RecurringRuleResult{}, errs.New(errs.InvalidInput).Explain("A description is required.").Field("description")
	}

	schedule, err := buildSchedule(cmd.Schedule)
	if err != nil {
		return RecurringRuleResult{}, wrapRecurringError(err)
	}

	startsOn, err := normalize.DateOf(cmd.StartsOn, s.Clock, s.Config.UserTimezone)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "starts_on")
	}

	var opts []recurring.RecurringRuleOption
	endsOn, err := optionalDate(cmd.EndsOn, s.Clock, s.Config.UserTimezone)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "ends_on")
	}
	if endsOn != nil {
		opts = append(opts, recurring.WithEndsOn(*endsOn))
	}

	rule, err := recurring.NewRecurringRule(
		s.IDs.NewID(), cmd.ActorID, account.ID(), category.ID(), amountMinor, description, schedule, startsOn, opts...,
	)
	if err != nil {
		return RecurringRuleResult{}, wrapRecurringError(err)
	}

	if err := s.RecurringRules.Create(ctx, cmd.ActorID, rule); err != nil {
		return RecurringRuleResult{}, err
	}
	return RecurringRuleResult{Rule: rule, Currency: account.Currency()}, nil
}

// UpdateRecurringRuleCommand updates an existing rule's amount,
// description, schedule, and ends_on. AccountRef, CategoryRef, and StartsOn
// are fixed at creation and not exposed here:
//
//   - The account/category pair decides which ledger a materialised
//     occurrence posts to and which direction the money moves (ADR-0014).
//     Changing either retroactively reinterprets every already-generated
//     pending occurrence's meaning — indistinguishable from archiving this
//     rule and creating a new one, the same reasoning that keeps a budget
//     line's category fixed once created (RemoveBudgetLine + AddBudgetLine
//     is that operation instead of a third way to express it).
//   - StartsOn is the schedule's anchor (ADR-0014): every firing is computed
//     from it, so moving it would retroactively shift what date
//     already-generated occurrences represent, and no occurrence-
//     reconciliation logic exists yet (that's #278's foundation, not this
//     issue's).
//
// EndsOn is full-replace, like UpdateBudget's StartsOn: passing it empty
// clears it to "runs indefinitely" rather than leaving a prior value
// untouched, since there is no separate "don't change this" sentinel on a
// plain string field.
//
// If Schedule actually changes the firing pattern, this discards and
// regenerates the rule's pending future occurrences (ADR-0014) — see
// regenerateAfterScheduleChange. An amount/description/ends_on-only edit
// never touches occurrences.
type UpdateRecurringRuleCommand struct {
	ActorID     string
	RuleID      string
	Amount      string
	Description string
	Schedule    RecurringScheduleInput
	EndsOn      string
}

// UpdateRecurringRule implements the "update" use case in issue #277's
// recurring-rule-CRUD scope, extended by issue #278 to regenerate
// occurrences when the schedule itself changes.
func (s *Service) UpdateRecurringRule(ctx context.Context, cmd UpdateRecurringRuleCommand) (RecurringRuleResult, error) {
	if err := requireActorID(cmd.ActorID); err != nil {
		return RecurringRuleResult{}, err
	}
	existing, err := s.RecurringRules.Get(ctx, cmd.ActorID, cmd.RuleID)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "rule_id")
	}

	account, err := s.resolveOwnedAccount(ctx, cmd.ActorID, existing.AccountID())
	if err != nil {
		return RecurringRuleResult{}, err
	}
	amountMinor, err := normalize.Amount(cmd.Amount, account.Currency())
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "amount")
	}

	description, err := normalize.Text(cmd.Description, maxRuleDescriptionLen)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "description")
	}
	if description == "" {
		return RecurringRuleResult{}, errs.New(errs.InvalidInput).Explain("A description is required.").Field("description")
	}

	schedule, err := buildSchedule(cmd.Schedule)
	if err != nil {
		return RecurringRuleResult{}, wrapRecurringError(err)
	}

	var opts []recurring.RecurringRuleOption
	endsOn, err := optionalDate(cmd.EndsOn, s.Clock, s.Config.UserTimezone)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "ends_on")
	}
	if endsOn != nil {
		opts = append(opts, recurring.WithEndsOn(*endsOn))
	}
	opts = append(opts, recurringArchivedAtOptions(existing)...)

	updated, err := recurring.NewRecurringRule(
		existing.ID(), existing.UserID(), existing.AccountID(), existing.CategoryID(),
		amountMinor, description, schedule, existing.StartsOn(), opts...,
	)
	if err != nil {
		return RecurringRuleResult{}, wrapRecurringError(err)
	}

	if err := s.RecurringRules.Update(ctx, cmd.ActorID, updated); err != nil {
		return RecurringRuleResult{}, err
	}

	if !scheduleEqual(existing.Schedule(), updated.Schedule()) {
		if err := s.regenerateAfterScheduleChange(ctx, cmd.ActorID, updated); err != nil {
			return RecurringRuleResult{}, err
		}
	}
	return RecurringRuleResult{Rule: updated, Currency: account.Currency()}, nil
}

// ArchiveRecurringRuleCommand stops a rule from generating any further
// occurrences going forward, while leaving the rule and its already-
// generated materialised/skipped occurrences fully queryable.
type ArchiveRecurringRuleCommand struct {
	ActorID string
	RuleID  string
}

// ArchiveRecurringRule implements the "archive" use case in issue #277's
// recurring-rule-CRUD scope, extended by issue #278 to cancel a newly-
// archived rule's still-pending occurrences. Archiving an already-archived
// rule is a no-op that returns its current state unchanged, the same
// idempotency ArchiveBudget/ArchiveAccount give — and, since nothing
// changed, it does not re-run occurrence cancellation either.
//
// There is no "cancelled" OccurrenceStatus in the domain model — only
// pending/materialised/skipped, and MarkSkipped represents a user's own
// decision, which an archive-triggered cleanup isn't — so cancellation here
// means removing the rows outright via DeletePending, which by construction
// only ever touches pending occurrences and leaves materialised/skipped
// history untouched.
func (s *Service) ArchiveRecurringRule(ctx context.Context, cmd ArchiveRecurringRuleCommand) (RecurringRuleResult, error) {
	if err := requireActorID(cmd.ActorID); err != nil {
		return RecurringRuleResult{}, err
	}
	existing, err := s.RecurringRules.Get(ctx, cmd.ActorID, cmd.RuleID)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "rule_id")
	}
	account, err := s.resolveOwnedAccount(ctx, cmd.ActorID, existing.AccountID())
	if err != nil {
		return RecurringRuleResult{}, err
	}
	if existing.Archived() {
		return RecurringRuleResult{Rule: existing, Currency: account.Currency()}, nil
	}

	today, err := normalize.DateOf("", s.Clock, s.Config.UserTimezone)
	if err != nil {
		return RecurringRuleResult{}, err
	}

	var opts []recurring.RecurringRuleOption
	if endsOn, ok := existing.EndsOn(); ok {
		opts = append(opts, recurring.WithEndsOn(endsOn))
	}
	opts = append(opts, recurring.WithArchivedAt(today))

	updated, err := recurring.NewRecurringRule(
		existing.ID(), existing.UserID(), existing.AccountID(), existing.CategoryID(),
		existing.AmountMinor(), existing.Description(), existing.Schedule(), existing.StartsOn(), opts...,
	)
	if err != nil {
		return RecurringRuleResult{}, wrapRecurringError(err)
	}

	if err := s.RecurringRules.Update(ctx, cmd.ActorID, updated); err != nil {
		return RecurringRuleResult{}, err
	}
	if err := s.ScheduledOccurrences.DeletePending(ctx, cmd.ActorID, existing.ID(), existing.StartsOn()); err != nil {
		return RecurringRuleResult{}, err
	}
	return RecurringRuleResult{Rule: updated, Currency: account.Currency()}, nil
}

// GetRecurringRuleQuery fetches a single recurring rule by ID, scoped to
// the actor the same way every other recurring-rule use case is
// (ADR-0006).
type GetRecurringRuleQuery struct {
	ActorID string
	RuleID  string
}

// GetRecurringRule implements the "fetch one" read this issue's CRUD
// needs.
func (s *Service) GetRecurringRule(ctx context.Context, q GetRecurringRuleQuery) (RecurringRuleResult, error) {
	if err := requireActorID(q.ActorID); err != nil {
		return RecurringRuleResult{}, err
	}
	rule, err := s.RecurringRules.Get(ctx, q.ActorID, q.RuleID)
	if err != nil {
		return RecurringRuleResult{}, attachField(err, "rule_id")
	}
	account, err := s.resolveOwnedAccount(ctx, q.ActorID, rule.AccountID())
	if err != nil {
		return RecurringRuleResult{}, err
	}
	return RecurringRuleResult{Rule: rule, Currency: account.Currency()}, nil
}

// ListRecurringRulesQuery lists every rule actorID owns, archived and
// active alike — filtering to "current" is a surface/UI concern, the same
// as ListBudgets/ListAccounts.
type ListRecurringRulesQuery struct {
	ActorID string
}

// ListRecurringRulesResult is ListRecurringRules' result, in the
// repository's most-recently-created-first order. Currencies maps each
// rule's own ID to the currency its AmountMinor is denominated in
// (RecurringRuleResult's own doc comment explains why this can't live on
// RecurringRule itself) — a map alongside Rules rather than a parallel
// wrapper slice, so a caller that only wants the rules themselves (e.g.
// GenerateOccurrences' own RecurringRules.List call, which this method
// doesn't share — this is the surface-facing read) isn't forced through
// an extra indirection.
type ListRecurringRulesResult struct {
	Rules      []recurring.RecurringRule
	Currencies map[string]string
}

// ListRecurringRules implements the "list" read this issue's CRUD needs.
// Currencies is built from one Accounts.List call, not one lookup per
// rule — the same "resolve the whole owning set once" shape Forecast's
// own accountByID cache uses, since a surface can't resolve an account's
// currency itself.
func (s *Service) ListRecurringRules(ctx context.Context, q ListRecurringRulesQuery) (ListRecurringRulesResult, error) {
	if err := requireActorID(q.ActorID); err != nil {
		return ListRecurringRulesResult{}, err
	}
	rules, err := s.RecurringRules.List(ctx, q.ActorID)
	if err != nil {
		return ListRecurringRulesResult{}, err
	}
	accounts, err := s.Accounts.List(ctx, q.ActorID)
	if err != nil {
		return ListRecurringRulesResult{}, err
	}
	currencyByAccountID := make(map[string]string, len(accounts))
	for _, a := range accounts {
		currencyByAccountID[a.ID()] = a.Currency()
	}
	currencies := make(map[string]string, len(rules))
	for _, r := range rules {
		currencies[r.ID()] = currencyByAccountID[r.AccountID()]
	}
	return ListRecurringRulesResult{Rules: rules, Currencies: currencies}, nil
}

// buildSchedule dispatches in to whichever recurring.New*Schedule
// constructor its Frequency names, per ADR-0014's supported RRULE subset.
// An unrecognised frequency string is the one validation this function
// does itself (InvalidInput, field "schedule.frequency"); every other
// rejection (a bad interval, weekday, day-of-month, or month) is the
// corresponding constructor's own sentinel error, translated by
// wrapRecurringError.
func buildSchedule(in RecurringScheduleInput) (recurring.Schedule, error) {
	switch recurring.Frequency(in.Frequency) {
	case recurring.FrequencyWeekly:
		return recurring.NewWeeklySchedule(in.Interval, in.Weekday)
	case recurring.FrequencyMonthly:
		return recurring.NewMonthlySchedule(in.Interval, in.DayOfMonth)
	case recurring.FrequencyYearly:
		return recurring.NewYearlySchedule(in.Interval, in.Month, in.DayOfMonth)
	default:
		return recurring.Schedule{}, errs.New(errs.InvalidInput).
			Explain("%q isn't a supported recurrence frequency.", in.Frequency).
			Field("schedule.frequency").
			With("valid_frequencies", []string{"weekly", "monthly", "yearly"})
	}
}

// recurringArchivedAtOptions carries rule's archived state forward into a
// reconstructed RecurringRule — the same reconstruction-not-re-derivation
// shape budgetArchivedAtOptions gives budgeting.NewBudget, adapted to
// recurring.NewRecurringRule's functional-option shape.
func recurringArchivedAtOptions(rule recurring.RecurringRule) []recurring.RecurringRuleOption {
	if d, ok := rule.ArchivedAt(); ok {
		return []recurring.RecurringRuleOption{recurring.WithArchivedAt(d)}
	}
	return nil
}

// wrapRecurringError translates internal/domain/recurring's sentinel
// errors into user-safe *errs.Error values, the same role wrapBudgetingError
// plays for internal/domain/budgeting. The Err*NotPositive/EndsBeforeStart/
// Schedule* sentinels are reachable from genuine user input (a bad amount,
// ends_on, or schedule shape); the empty-ID/empty-description ones are
// defensive, since every use case above already validates the
// corresponding input (resolveOwnedAccount/resolveOwnedCategory,
// normalize.Text, s.IDs.NewID()) before reaching this call.
func wrapRecurringError(err error) error {
	if err == nil {
		return nil
	}
	var e *errs.Error
	if errors.As(err, &e) {
		return e
	}
	switch {
	case errors.Is(err, recurring.ErrRuleAmountNotPositive):
		return errs.New(errs.InvalidInput).
			Explain("A recurring rule's amount must be greater than zero.").
			Field("amount")
	case errors.Is(err, recurring.ErrRuleEndsBeforeStart):
		return errs.New(errs.InvalidInput).
			Explain("A rule's end date can't be before its start date.").
			Field("ends_on")
	case errors.Is(err, recurring.ErrScheduleIntervalNotPositive):
		return errs.New(errs.InvalidInput).
			Explain("A recurrence interval must be at least 1.").
			Field("schedule.interval")
	case errors.Is(err, recurring.ErrScheduleInvalidWeekday):
		return errs.New(errs.InvalidInput).
			Explain("That isn't a valid weekday for a weekly recurrence.").
			Field("schedule.weekday")
	case errors.Is(err, recurring.ErrScheduleInvalidDayOfMonth):
		return errs.New(errs.InvalidInput).
			Explain("A day of month must be between 1 and 31.").
			Field("schedule.day_of_month")
	case errors.Is(err, recurring.ErrScheduleInvalidMonth):
		return errs.New(errs.InvalidInput).
			Explain("That isn't a valid month for a yearly recurrence.").
			Field("schedule.month")
	case errors.Is(err, recurring.ErrScheduleInvalidFrequency):
		return errs.New(errs.InvalidInput).
			Explain("That isn't a supported recurrence frequency.").
			Field("schedule.frequency")
	case errors.Is(err, recurring.ErrOccurrenceInvalidTransition):
		// Reachable from genuine (if racy) user input: materialising or
		// skipping an occurrence that's already materialised or skipped
		// (issue #279). Conflict, the same code family this codebase uses
		// elsewhere for "the thing you're acting on is no longer in the
		// state you expected" (e.g. memScheduledOccurrences.CreateBatch's
		// duplicate-date case).
		return errs.New(errs.Conflict).
			Explain("This occurrence has already been materialised or skipped.").
			Field("occurrence_id")
	default:
		// ErrRuleEmptyID/EmptyUserID/EmptyAccountID/EmptyCategoryID/
		// EmptyDescription/InvalidSchedule, and the occurrence-side
		// ErrOccurrenceEmptyID/EmptyRuleID/InvalidStatus/
		// EmptyTransactionID/UnexpectedTransactionID, are all defensive
		// here: every use case above already validated the corresponding
		// input before reaching this call, so reaching this branch would
		// mean this package's own invariant broke, not that the user did
		// anything wrong — Internal, the same reasoning
		// wrapBudgetingError's default case gives.
		return errs.New(errs.Internal).Explain("That recurring rule isn't valid.").Wrap(err)
	}
}
