// This file implements issue #281's write-tier MCP wiring for recurring
// rules and occurrences: create_recurring_rule, update_recurring_rule,
// materialise_occurrence, and skip_occurrence, wired onto
// internal/app/recurring_rules.go's CreateRecurringRule/UpdateRecurringRule
// (issue #277) and internal/app/recurring_occurrences_actions.go's
// MaterialiseOccurrence/SkipOccurrence (issue #279) — following
// budgets_write.go's own write-tier tool conventions.
package mcp

import (
	"context"
	"encoding/json"
	"time"

	sdkmcp "github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/anirudhgray/bodger/internal/app"
	"github.com/anirudhgray/bodger/internal/ports"
)

// scheduleInputArgs is a recurring rule's schedule as sent by a caller,
// mirroring internal/surface/http's own scheduleRequest field for field.
// Every field is always sent; buildSchedule (internal/app/recurring_rules.go)
// reads only the subset its Frequency actually needs.
type scheduleInputArgs struct {
	Frequency  string `json:"frequency"`
	Interval   int    `json:"interval"`
	Weekday    int    `json:"weekday,omitempty"`
	DayOfMonth int    `json:"day_of_month,omitempty"`
	Month      int    `json:"month,omitempty"`
}

func (s scheduleInputArgs) input() app.RecurringScheduleInput {
	return app.RecurringScheduleInput{
		Frequency: s.Frequency, Interval: s.Interval,
		Weekday: time.Weekday(s.Weekday), DayOfMonth: s.DayOfMonth, Month: time.Month(s.Month),
	}
}

// scheduleInputSchema is the JSON Schema fragment for one scheduleInputArgs
// value, shared by create_recurring_rule's and update_recurring_rule's own
// "schedule" property.
func scheduleInputSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"frequency": map[string]any{
				"type":        "string",
				"enum":        []string{"weekly", "monthly", "yearly"},
				"description": "The recurrence frequency.",
			},
			"interval": map[string]any{
				"type":        "integer",
				"description": "Fire every this many weeks/months/years.",
			},
			"weekday": map[string]any{
				"type":        "integer",
				"description": "0 (Sunday) - 6 (Saturday). Required for a weekly schedule.",
			},
			"day_of_month": map[string]any{
				"type":        "integer",
				"description": "1-31. Required for a monthly or yearly schedule.",
			},
			"month": map[string]any{
				"type":        "integer",
				"description": "1 (January) - 12 (December). Required for a yearly schedule.",
			},
		},
		"required":             []string{"frequency", "interval"},
		"additionalProperties": false,
	}
}

// createRecurringRuleArgs is create_recurring_rule's arguments, mirroring
// internal/surface/http's createRecurringRuleRequest field for field.
type createRecurringRuleArgs struct {
	AccountRef  string            `json:"account_ref"`
	CategoryRef string            `json:"category_ref"`
	Amount      string            `json:"amount"`
	Description string            `json:"description"`
	Schedule    scheduleInputArgs `json:"schedule"`
	StartsOn    string            `json:"starts_on,omitempty"`
	EndsOn      string            `json:"ends_on,omitempty"`
}

// createRecurringRuleTool wires app.Service.CreateRecurringRule onto a
// write-tier MCP tool.
func createRecurringRuleTool() ToolDef {
	return ToolDef{
		Name:        "create_recurring_rule",
		Description: "Create a recurring rule's template. No occurrence is generated by this call. The direction of the money (an outflow or an inflow) follows from the category's own kind.",
		Tier:        ports.MCPToolTierWrite,
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"account_ref": map[string]any{
					"type":        "string",
					"description": "The account a materialised occurrence would post to: an account's ID or unique name.",
				},
				"category_ref": map[string]any{
					"type":        "string",
					"description": "The category a materialised occurrence would be attributed to, which also decides its direction.",
				},
				"amount": map[string]any{
					"type":        "string",
					"description": "The planned amount, in the account's own currency. Always positive.",
				},
				"description": map[string]any{
					"type": "string",
				},
				"schedule": scheduleInputSchema(),
				"starts_on": map[string]any{
					"type":        "string",
					"description": "The first date the rule may fire on. Defaults to today.",
				},
				"ends_on": map[string]any{
					"type":        "string",
					"description": "The last date the rule may fire on. Omit for a rule that runs indefinitely.",
				},
			},
			"required":             []string{"account_ref", "category_ref", "amount", "description", "schedule"},
			"additionalProperties": false,
		},
		Execute: func(ctx context.Context, svc *app.Service, actorID string, raw json.RawMessage) (*sdkmcp.CallToolResult, error) {
			var args createRecurringRuleArgs
			if err := decodeArgs(raw, &args); err != nil {
				return errorResult(err), nil
			}

			result, err := svc.CreateRecurringRule(ctx, app.CreateRecurringRuleCommand{
				ActorID:     actorID,
				AccountRef:  args.AccountRef,
				CategoryRef: args.CategoryRef,
				Amount:      args.Amount,
				Description: args.Description,
				Schedule:    args.Schedule.input(),
				StartsOn:    args.StartsOn,
				EndsOn:      args.EndsOn,
			})
			if err != nil {
				return errorResult(err), nil
			}
			return recurringRuleResultResult(result)
		},
	}
}

// updateRecurringRuleArgs is update_recurring_rule's arguments, mirroring
// internal/surface/http's patchRecurringRuleRequest: a full replacement
// of every editable field (app.UpdateRecurringRuleCommand's own doc
// comment -- omitting ends_on clears it to "runs indefinitely", not to
// the rule's existing value).
type updateRecurringRuleArgs struct {
	RuleID      string            `json:"rule_id"`
	Amount      string            `json:"amount"`
	Description string            `json:"description"`
	Schedule    scheduleInputArgs `json:"schedule"`
	EndsOn      string            `json:"ends_on,omitempty"`
}

// updateRecurringRuleTool wires app.Service.UpdateRecurringRule onto a
// write-tier MCP tool.
func updateRecurringRuleTool() ToolDef {
	return ToolDef{
		Name:        "update_recurring_rule",
		Description: "Update a recurring rule's amount, description, schedule, and end date. This is a full replacement of every editable field -- resend the current ends_on if only something else is changing, since omitting it clears the rule to run indefinitely. The rule's account, category, and starts-on date can't change. If the schedule's own firing pattern actually changes, the rule's pending future occurrences are discarded and regenerated.",
		Tier:        ports.MCPToolTierWrite,
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"rule_id": map[string]any{
					"type":        "string",
					"description": "The rule's ID.",
				},
				"amount": map[string]any{
					"type":        "string",
					"description": "The planned amount, in the rule's account's own currency. Always positive.",
				},
				"description": map[string]any{
					"type": "string",
				},
				"schedule": scheduleInputSchema(),
				"ends_on": map[string]any{
					"type":        "string",
					"description": "Omitting this clears the rule to run indefinitely -- it does not leave the existing ends_on untouched.",
				},
			},
			"required":             []string{"rule_id", "amount", "description", "schedule"},
			"additionalProperties": false,
		},
		Execute: func(ctx context.Context, svc *app.Service, actorID string, raw json.RawMessage) (*sdkmcp.CallToolResult, error) {
			var args updateRecurringRuleArgs
			if err := decodeArgs(raw, &args); err != nil {
				return errorResult(err), nil
			}

			result, err := svc.UpdateRecurringRule(ctx, app.UpdateRecurringRuleCommand{
				ActorID:     actorID,
				RuleID:      args.RuleID,
				Amount:      args.Amount,
				Description: args.Description,
				Schedule:    args.Schedule.input(),
				EndsOn:      args.EndsOn,
			})
			if err != nil {
				return errorResult(err), nil
			}
			return recurringRuleResultResult(result)
		},
	}
}

// scheduledOccurrenceViewFromOccurrence builds a scheduledOccurrenceView
// from an occurrence's already-extracted fields -- shared by
// materialise_occurrence's own occurrence half and skip_occurrence's
// whole result, without either needing to name recurring.ScheduledOccurrence
// as a function parameter type (this package never imports
// internal/domain/recurring).
func scheduledOccurrenceViewFromOccurrence(id, ruleID, occurrenceDate, status, transactionID string) scheduledOccurrenceView {
	return scheduledOccurrenceView{
		ID: id, RuleID: ruleID, OccurrenceDate: occurrenceDate, Status: status, TransactionID: transactionID,
	}
}

// materialiseOccurrenceArgs is materialise_occurrence's arguments.
type materialiseOccurrenceArgs struct {
	OccurrenceID string `json:"occurrence_id"`
}

// materialiseOccurrenceView is materialise_occurrence's result shape
// (app.MaterialiseOccurrenceResult): the transaction it produced, and the
// occurrence's own updated state.
type materialiseOccurrenceView struct {
	Occurrence  scheduledOccurrenceView `json:"occurrence"`
	Transaction transactionView         `json:"transaction"`
}

// materialiseOccurrenceTool wires app.Service.MaterialiseOccurrence onto a
// write-tier MCP tool.
func materialiseOccurrenceTool() ToolDef {
	return ToolDef{
		Name:        "materialise_occurrence",
		Description: "Turn a pending occurrence into a real transaction, always using the occurrence's owning rule's current amount, account, category, and description, and the occurrence's own projected date. There is no way to override any of these for this one materialisation -- materialise with the projected fields, then edit_transaction the result, to record it with a different amount or date.",
		Tier:        ports.MCPToolTierWrite,
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"occurrence_id": map[string]any{
					"type":        "string",
					"description": "The occurrence's ID.",
				},
			},
			"required":             []string{"occurrence_id"},
			"additionalProperties": false,
		},
		Execute: func(ctx context.Context, svc *app.Service, actorID string, raw json.RawMessage) (*sdkmcp.CallToolResult, error) {
			var args materialiseOccurrenceArgs
			if err := decodeArgs(raw, &args); err != nil {
				return errorResult(err), nil
			}

			result, err := svc.MaterialiseOccurrence(ctx, app.MaterialiseOccurrenceCommand{
				ActorID: actorID, OccurrenceID: args.OccurrenceID,
			})
			if err != nil {
				return errorResult(err), nil
			}
			txID, _ := result.Occurrence.TransactionID()
			return jsonResult(materialiseOccurrenceView{
				Occurrence: scheduledOccurrenceViewFromOccurrence(
					result.Occurrence.ID(), result.Occurrence.RuleID(), result.Occurrence.OccurrenceDate().String(),
					string(result.Occurrence.Status()), txID,
				),
				Transaction: transactionViewFrom(app.TransactionResult{Transaction: result.Transaction}),
			})
		},
	}
}

// skipOccurrenceArgs is skip_occurrence's arguments.
type skipOccurrenceArgs struct {
	OccurrenceID string `json:"occurrence_id"`
}

// skipOccurrenceTool wires app.Service.SkipOccurrence onto a write-tier
// MCP tool.
func skipOccurrenceTool() ToolDef {
	return ToolDef{
		Name:        "skip_occurrence",
		Description: "Record that a pending occurrence's firing was deliberately not recorded. No transaction is created -- money never moved and never will for this occurrence's date.",
		Tier:        ports.MCPToolTierWrite,
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"occurrence_id": map[string]any{
					"type":        "string",
					"description": "The occurrence's ID.",
				},
			},
			"required":             []string{"occurrence_id"},
			"additionalProperties": false,
		},
		Execute: func(ctx context.Context, svc *app.Service, actorID string, raw json.RawMessage) (*sdkmcp.CallToolResult, error) {
			var args skipOccurrenceArgs
			if err := decodeArgs(raw, &args); err != nil {
				return errorResult(err), nil
			}

			result, err := svc.SkipOccurrence(ctx, app.SkipOccurrenceCommand{ActorID: actorID, OccurrenceID: args.OccurrenceID})
			if err != nil {
				return errorResult(err), nil
			}
			txID, _ := result.Occurrence.TransactionID()
			return jsonResult(scheduledOccurrenceViewFromOccurrence(
				result.Occurrence.ID(), result.Occurrence.RuleID(), result.Occurrence.OccurrenceDate().String(),
				string(result.Occurrence.Status()), txID,
			))
		},
	}
}
